services:
  - type: web
    name: chongsleeptuantra
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && PLAYWRIGHT_BROWSERS_PATH=0 python -m playwright install chromium
    startCommand: python keep_alive.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
